teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: false
    axis_linear:  # Left thumb stick vertical
      x: 1
      y: 0
    scale_linear:
      x: 5.0
      y: 5.0

    axis_angular:  # Right thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 3.14159
      
    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
