controller_manager:
  ros__parameters:
    update_rate: 100
    joint1_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint1
      gains:
        p: 10.0
        i: 0.1
        d: 0.01

    joint2_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - joint2
      gains:
        p: 5.0
