controller_manager:
  ros__parameters:
    update_rate: 5

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    front_left_steer_controller:
      type: position_controllers/JointGroupPositionController

    front_left_drive_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    front_right_steer_controller:
      type: position_controllers/JointGroupPositionController

    front_right_drive_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    rear_left_steer_controller:
      type: position_controllers/JointGroupPositionController

    rear_left_drive_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    rear_right_steer_controller:
      type: position_controllers/JointGroupPositionController

    rear_right_drive_controller:
      type: velocity_controllers/JointGroupVelocityController

front_left_steer_controller:
  ros__parameters:
    joints:
      - front_left_steer
    gains:
      p: 10.0
      i: 0.1
      d: 0.01

front_left_drive_controller:
  ros__parameters:
    joints:
      - front_left_drive
    gains:
      p: 0.1

front_right_steer_controller:
  ros__parameters:
    joints:
      - front_right_steer
    gains:
      p: 10.0
      i: 0.1
      d: 0.01

front_right_drive_controller:
  ros__parameters:
    joints:
      - front_right_drive
    gains:
      p: 0.1


rear_left_steer_controller:
  ros__parameters:
    joints:
      - rear_left_steer
    gains:
      p: 10.0
      i: 0.1
      d: 0.01

rear_left_drive_controller:
  ros__parameters:
    joints:
      - rear_left_drive
    gains:
      p: 0.1

rear_right_steer_controller:
  ros__parameters:
    joints:
      - rear_right_steer
    gains:
      p: 10.0
      i: 0.1
      d: 0.01

rear_right_drive_controller:
  ros__parameters:
    joints:
      - rear_right_drive
    gains:
      p: 0.1


