controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    shoulder_position_controller:
      type: position_controllers/JointGroupPositionController

    wrist_position_controller:
      # type: velocity_controllers/JointGroupVelocityController
      type: effort_controllers/JointGroupEffortController


shoulder_position_controller:
  ros__parameters:
    joints:
      - shoulder
    gains:
      p: 10.0
      i: 0.1
      d: 0.01

wrist_position_controller:
  ros__parameters:
    joints:
      - wrist
    gains:
      p: 0.1

